### ISSUE TITLE
Rails 4 Compatibility

### ISSUE THREAD

**Issue by georgediaz88** [dnagir/ios-checkboxes#13]
Hey there!

Any plans to relax the rails dependency in the gemspec `s.add_dependency "rails", "~> 3.1"` so that it's compatible with Rails4 projects? We're currently in the midst of an upgrade and I was curious if you wanted to tweak that dependency in the .gemspec so it could work for Rails4? Let me know what you think.

Thanks.

**Comment by dnagir** [comment]
No problem easing it up.

But I simply don't have enough time to maintain this gem anymore. So would be good if you could at least submit a ready-to-go PR or maybe take over the gem altogether.

**Comment by georgediaz88** [comment]
Thanks for the response. I added a pull request adding the compatibility. Feel free to merge this and release to rubygems.

Unfortunately, I won't be able to take over the gem but I'll PR anything back if I find it needs urgent fixing.

Thanks!

**Comment by dnagir** [comment]
Closing due to #14. Thanks for the PR.
