### ISSUE TITLE
TypeError: $.browser is undefined

### ISSUE THREAD

**Issue by glafir** [dnagir/ios-checkboxes#15]
In rails 3.2.21 I got this error:

TypeError: $.browser is undefined

Near this:
iOSCheckbox.prototype.disableTextSelection = function() {
      if ($.browser.msie) {
        return $([this.handle, this.offLabel, this.onLabel, this.container]).attr("unselectable", "on");
      }
    };

**Comment by dnagir** [comment]
This error shouldn't have anything to do with the gem. The `$.browser` was removed from jQuery 1.9.
